.. table::
 :width: 100 
 :widths: 20 15 25 40 
 :class: tight-table

 +-----------------------+-------------+-------------------------+---------------------------------------+
 |Property name          |Type         |Default value \/         |Description                            |
 |                       |             |mandatory                |                                       |
 +=======================+=============+=========================+=======================================+
 |xuudb.aclFile          |filesystem   |\-                       |File with DNs of clients authorised to |
 |                       |path         |                         |access protected XUUDB services.       |
 +-----------------------+-------------+-------------------------+---------------------------------------+
 |xuudb.address          |string       |\http:\/\/localhost:34463|HTTPS or HTTP URL where the server     |
 |                       |             |                         |should listen.                         |
 +-----------------------+-------------+-------------------------+---------------------------------------+
 |xuudb.db.[.\*]         |string can   |\-                       |Properties with this prefix are used   |
 |                       |have subkeys |                         |to configure database backend, used by |
 |                       |             |                         |XUUDB. See separate documentation for  |
 |                       |             |                         |details.                               |
 +-----------------------+-------------+-------------------------+---------------------------------------+
 |xuudb.                 |filesystem   |conf\/                   |File with configuration of the dynamic |
 |dynamicAttributesConfig|path         |dynamicAttributesCfg.xml |part of the XUUDB.                     |
 +-----------------------+-------------+-------------------------+---------------------------------------+
 |xuudb.protectAll       |[true, false]|false                    |If true then access to both query and  |
 |                       |             |                         |modify operations are protected by ACL.|
 |                       |             |                         |If false then only modification        |
 |                       |             |                         |operations are protected.              |
 +-----------------------+-------------+-------------------------+---------------------------------------+
 |xuudb.type             |[dn]         |dn                       |DEPRECATED and no longer required.     |
 +-----------------------+-------------+-------------------------+---------------------------------------+
