.. table:: 
 :width: 100 
 :widths: 20 15 15 50 
 :class: tight-table

 +----------------------+--------------+-------------+-------------------------------------------------+
 |Property name         |Type          |Default value|Description                                      |
 |                      |              |             |                                                 |
 |                      |              |\/ mandatory |                                                 |
 +======================+==============+=============+=================================================+
 |xuudb.client.         |[true, false] |true         |Controls whether signing of key web service      |
 |                      |              |             |                                                 |
 |digitalSigningEnabled |              |             |requests should be performed.                    |
 +----------------------+--------------+-------------+-------------------------------------------------+
 |xuudb.client.         |[true, false] |false        |Whether HTTP basic authentication should be used.|
 |                      |              |             |                                                 |
 |httpAuthnEnabled      |              |             |                                                 |
 +----------------------+--------------+-------------+-------------------------------------------------+
 |xuudb.client.         |string        |empty string |Password for use with HTTP basic authentication  |
 |                      |              |             |                                                 |
 |httpPassword          |              |             |(if enabled).                                    |
 +----------------------+--------------+-------------+-------------------------------------------------+
 |xuudb.client.         |string        |empty string |Username for use with HTTP basic authentication  |
 |                      |              |             |                                                 |
 |httpUser              |              |             |(if enabled).                                    |
 +----------------------+--------------+-------------+-------------------------------------------------+
 |xuudb.client.         |string        |empty string |Space separated list of additional handler class |
 |                      |              |             |                                                 |
 |inHandlers            |              |             |names for handling incoming WS messages          |
 +----------------------+--------------+-------------+-------------------------------------------------+
 |xuudb.client.         |integer number|3            |Controls how many times the client should try to |
 |                      |              |             |                                                 |
 |maxWsCallRetries      |              |             |call a failing web service. Note that only the   |
 |                      |              |             |                                                 |
 |                      |              |             |transient failure reasons cause the retry. Note  |
 |                      |              |             |                                                 |
 |                      |              |             |that value of 0 enables unlimited number of      |
 |                      |              |             |                                                 |
 |                      |              |             |retries, while value of 1 means that only one    |
 |                      |              |             |                                                 |
 |                      |              |             |call is tried.                                   |
 +----------------------+--------------+-------------+-------------------------------------------------+
 |xuudb.client.         |[true, false] |false        |Controls whether messages should be logged (at   |
 |                      |              |             |                                                 |
 |messageLogging        |              |             |INFO level).                                     |
 +----------------------+--------------+-------------+-------------------------------------------------+
 |xuudb.client.         |string        |empty string |Space separated list of additional handler class |
 |                      |              |             |                                                 |
 |outHandlers           |              |             |names for handling outgoing WS messages          |
 +----------------------+--------------+-------------+-------------------------------------------------+
 |xuudb.client.         |[true, false] |true         |Controls whether security sessions should be     |
 |                      |              |             |                                                 |
 |securitySessions      |              |             |enabled.                                         |
 +----------------------+--------------+-------------+-------------------------------------------------+
 |xuudb.client.         |[NONE, WARN,  |WARN         |Controls whether server's hostname should be     |
 |                      |              |             |                                                 |
 |serverHostnameChecking|FAIL]         |             |checked for matching its certificate subject.    |
 |                      |              |             |                                                 |
 |                      |              |             |This verification prevents man\-in\-the\-middle  |
 |                      |              |             |                                                 |
 |                      |              |             |attacks. If enabled WARN will only print warning |
 |                      |              |             |                                                 |
 |                      |              |             |in log, FAIL will close the connection.          |
 +----------------------+--------------+-------------+-------------------------------------------------+
 |xuudb.client.         |[true, false] |true         |Controls whether SSL authentication of the       |
 |                      |              |             |                                                 |
 |sslAuthnEnabled       |              |             |client should be performed.                      |
 +----------------------+--------------+-------------+-------------------------------------------------+
 |xuudb.client.         |[true, false] |true         |Controls whether the SSL\/TLS connection mode is |
 |                      |              |             |                                                 |
 |sslEnabled            |              |             |enabled.                                         |
 +----------------------+--------------+-------------+-------------------------------------------------+
 |xuudb.client.         |integer number|10000        |Amount of milliseconds to wait before retry of a |
 |                      |              |             |                                                 |
 |wsCallRetryDelay      |              |             |failed web service call.                         |
 +----------------------+--------------+-------------+-------------------------------------------------+
 |xuudb.client.http.    |[true, false] |true         |If set to false, then the client will not use    |
 |                      |              |             |                                                 |
 |allow\-chunking       |              |             |HTTP 1.1 data chunking.                          |
 +----------------------+--------------+-------------+-------------------------------------------------+
 |xuudb.client.http.    |[true, false] |false        |If set to true then the client will send         |
 |                      |              |             |                                                 |
 |connection\-close     |              |             |connection close header, so the server will      |
 |                      |              |             |                                                 |
 |                      |              |             |close the socket.                                |
 +----------------------+--------------+-------------+-------------------------------------------------+
 |xuudb.client.http.    |integer number|20000        |Timeout for the connection establishing (ms)     |
 |                      |              |             |                                                 |
 |connection.timeout    |              |             |                                                 |
 +----------------------+--------------+-------------+-------------------------------------------------+
 |xuudb.client.http.    |integer number|6            |How many connections per host can be made. Note: |
 |                      |              |             |                                                 |
 |maxPerRoute           |              |             |this is a limit for a single client object       |
 |                      |              |             |                                                 |
 |                      |              |             |instance.                                        |
 +----------------------+--------------+-------------+-------------------------------------------------+
 |xuudb.client.http.    |integer number|3            |Maximum number of allowed HTTP redirects.        |
 |                      |              |             |                                                 |
 |maxRedirects          |              |             |                                                 |
 +----------------------+--------------+-------------+-------------------------------------------------+
 |xuudb.client.http.    |integer number|20           |How many connections in total can be made. Note: |
 |                      |              |             |                                                 |
 |maxTotal              |              |             |this is a limit for a single client object       |
 |                      |              |             |                                                 |
 |                      |              |             |instance.                                        |
 +----------------------+--------------+-------------+-------------------------------------------------+
 |xuudb.client.http.    |integer number|0            |Socket timeout (ms)                              |
 |                      |              |             |                                                 |
 |socket.timeout        |              |             |                                                 |
 +----------------------+--------------+-------------+-------------------------------------------------+
 |xuudb.client.http.    |string        |\-           |Space (single) separated list of hosts, for      |
 |                      |              |             |                                                 |
 |nonProxyHosts         |              |             |which the HTTP proxy should not be used.         |
 +----------------------+--------------+-------------+-------------------------------------------------+
 |xuudb.client.http.    |string        |\-           |Relevant only when using HTTP proxy: defines     |
 |                      |              |             |                                                 |
 |proxy.password        |              |             |password for authentication to the proxy.        |
 +----------------------+--------------+-------------+-------------------------------------------------+
 |xuudb.client.http.    |string        |\-           |Relevant only when using HTTP proxy: defines     |
 |                      |              |             |                                                 |
 |proxy.user            |              |             |username for authentication to the proxy.        |
 +----------------------+--------------+-------------+-------------------------------------------------+
 |xuudb.client.http.    |string        |\-           |If set then the HTTP proxy will be used, with    |
 |                      |              |             |                                                 |
 |proxyHost             |              |             |this hostname.                                   |
 +----------------------+--------------+-------------+-------------------------------------------------+
 |xuudb.client.http.    |integer number|\-           |HTTP proxy port. If not defined then system      |
 |                      |              |             |                                                 |
 |proxyPort             |              |             |property is consulted, and as a final fallback   |
 |                      |              |             |                                                 |
 |                      |              |             |80 is used.                                      |
 +----------------------+--------------+-------------+-------------------------------------------------+
 |xuudb.client.http.    |string        |HTTP         |HTTP proxy type: HTTP or SOCKS.                  |
 |                      |              |             |                                                 |
 |proxyType             |              |             |                                                 |
 +----------------------+--------------+-------------+-------------------------------------------------+
