.. table:: 
 :width: 100 
 :widths: 30 10 60 
 :class: tight-table

 +---------------------+--------------------------------------------------------+-------------------------------------------+
 |Property             |Values                                                  |Description                                |
 +=====================+========================================================+===========================================+
 |status               |UNKNOWN,                                                |The status of the job                      |
 |                     |STAGINGIN, READY, QUEUED, STAGINGOUT, FAILED, SUCCESSFUL|                                           |
 +---------------------+--------------------------------------------------------+-------------------------------------------+
 |statusMessage        |string                                                  |status \/ error summary message            |
 +---------------------+--------------------------------------------------------+-------------------------------------------+
 |name                 |string                                                  |Job name as submitted, or "N\/A"           |
 +---------------------+--------------------------------------------------------+-------------------------------------------+
 |log                  |string                                                  |Execution log                              |
 +---------------------+--------------------------------------------------------+-------------------------------------------+
 |exitCode             |integer                                                 |exit code of the application (if available)|
 +---------------------+--------------------------------------------------------+-------------------------------------------+
 |queue                |string                                                  |batch queue, or "N\/A"                     |
 +---------------------+--------------------------------------------------------+-------------------------------------------+
 |submissionTime       |date\-                                                  |job submission time                        |
 |                     |time                                                    |                                           |
 +---------------------+--------------------------------------------------------+-------------------------------------------+
 |terminationTime      |date\-                                                  |time of automated job cleanup              |
 |                     |time                                                    |                                           |
 +---------------------+--------------------------------------------------------+-------------------------------------------+
 |currentTime          |date\-                                                  |current server time                        |
 |                     |time                                                    |                                           |
 +---------------------+--------------------------------------------------------+-------------------------------------------+
 |owner                |X500 name                                               |job owner (who submitted it)               |
 +---------------------+--------------------------------------------------------+-------------------------------------------+
 |acl                  |acl                                                     |access control list                        |
 +---------------------+--------------------------------------------------------+-------------------------------------------+
 |submissionPreferences|map                                                     |user preferences (uid, gid) if applicable  |
 +---------------------+--------------------------------------------------------+-------------------------------------------+
