.. table:: 
 :width: 100 
 :widths: 30 10 60 
 :class: tight-table

 +---------------------+-----------------+-----------------------------------------------------------+
 |URL                  |Method           |Description                                                |
 +=====================+=================+===========================================================+
 |\/                   |GET              |Get a list of all workflows accessible to the user         |
 +---------------------+-----------------+-----------------------------------------------------------+
 |\/?offset=           |GET              |List num workflows, starting at offset, with the given tags|
 +---------------------+-----------------+-----------------------------------------------------------+
 |\/                   |POST             |Submit a new workflow and start processing it              |
 |                     |application\/json|                                                           |
 +---------------------+-----------------+-----------------------------------------------------------+
 |\/id                 |GET              |Get a representation of the workflow with the given ID     |
 +---------------------+-----------------+-----------------------------------------------------------+
 |\/id\/actions\/abort |POST             |Abort the workflow with the given ID                       |
 +---------------------+-----------------+-----------------------------------------------------------+
 |\/id\/actions\/resume|POST             |Resume the workflow with the given ID, if in state "Held"  |
 +---------------------+-----------------+-----------------------------------------------------------+
 |\/id\/jobs?offset=   |GET              |Get a list of all jobs submitted for this workflow         |
 +---------------------+-----------------+-----------------------------------------------------------+
 |\/id\/files          |GET              |Get a list of the workflow files for this workflow         |
 +---------------------+-----------------+-----------------------------------------------------------+
