.. table:: 
 :width: 100 
 :widths: 30 70 
 :class: tight-table

 +---------------+-------------------------------------------------------+
 |Parameter      |Description                                            |
 +===============+=======================================================+
 |file           |the file on the storage, relative to storage root      |
 +---------------+-------------------------------------------------------+
 |target         |the target URL in case of "data push"                  |
 +---------------+-------------------------------------------------------+
 |source         |the source URL in case of "data pull"                  |
 +---------------+-------------------------------------------------------+
 |extraParameters|any additional parameters (e.g. number of UFTP streams)|
 +---------------+-------------------------------------------------------+
