.. table:: 
 :width: 100 
 :widths: 30 10 60 
 :class: tight-table

 +---------------------------+------+------------------------------------------------------+
 |URL                        |Method|Description                                           |
 +===========================+======+======================================================+
 |\/sites                    |GET   |Get a list of all sites                               |
 +---------------------------+------+------------------------------------------------------+
 |\/sites                    |POST  |Create a new site                                     |
 +---------------------------+------+------------------------------------------------------+
 |\/sites\/id                |GET   |Get a representation of the given site                |
 +---------------------------+------+------------------------------------------------------+
 |\/sites\/id                |DELETE|Destroy a site (but not the jobs)                     |
 +---------------------------+------+------------------------------------------------------+
 |\/sites\/id                |POST  |Submit a job to the site                              |
 +---------------------------+------+------------------------------------------------------+
 |\/sites\/id\/jobs?offset=  |GET   |List num jobs, starting at offset, with the given tags|
 +---------------------------+------+------------------------------------------------------+
 |\/sites\/id\/applications  |GET   |Get a list of all applications                        |
 +---------------------------+------+------------------------------------------------------+
 |\/sites\/id\/applications\/|GET   |Get a representation of the given application         |
 |appID                      |      |                                                      |
 +---------------------------+------+------------------------------------------------------+
