.. table:: 
 :width: 100 
 :widths: 30 20 50 
 :class: tight-table

 +---------------+------+----------------------------------+
 |URL            |Method|Description                       |
 +===============+======+==================================+
 |\/transfers    |GET   |Get a list of all transfers       |
 +---------------+------+----------------------------------+
 |\/transfers\/id|GET   |Get a representation of a transfer|
 +---------------+------+----------------------------------+
 |\/transfers\/id|DELETE|Abort and destroy the transfer    |
 +---------------+------+----------------------------------+
