.. _ucc_quickstart:

Getting started with UCC
------------------------

Assuming you have successfully installed UCC, this section
shows how to get going quickly.

.. _ucc_help:

Getting help
~~~~~~~~~~~~

Calling UCC with the ``-h`` option will show the available options. 
To get a list of available commands, type

.. code:: console

  $ ucc -h

To get help on a specific command, type

.. code:: console

  $  ucc <command> -h

See also :ref:`ucc_options` for a list of common options.


Connecting
~~~~~~~~~~

First, contact UNICORE and make sure you have access to some target systems.
  
.. code:: console

  $ ucc connect
  

List available sites
~~~~~~~~~~~~~~~~~~~~

Then, list the sites available to you using 
  
.. code:: console

  $ ucc list-sites


Running your first job
~~~~~~~~~~~~~~~~~~~~~~

The UCC distribution contains samples that you can run. Let's run the "date" 
sample. The ``-v`` switch prints more info so you can see what's going on.

.. code:: console

  $ ucc run -v [UCC_HOME]/samples/date.u

This will run "date" on a randomly chosen site, and retrieve the output. 
To run on a particular site, use the ``-s`` option to specify a particular 
target system.

.. note::
  Look for UCC samples in the ``/usr/share/doc/unicore/ucc/samples`` directory.


Listing your jobs
~~~~~~~~~~~~~~~~~

The command

.. code:: console

  $ ucc list-jobs -l

will print a list of jobs (actually their addresses) with their respective status 
(``RUNNING``, ``SUCCESSFUL``, etc)
  
