.. _ucc_scripting:

Scripting
---------

UCC can execute Groovy scripts. `Groovy <https://groovy-lang.org>`_ is a dynamic
scripting language similar to Python or Ruby, but very closely integrated with Java.
The scripting facility can be used for automation tasks or implementation of 
custom commands, but it needs a bit of insight into how UCC and UNICORE work.

Script context
~~~~~~~~~~~~~~

Your Groovy scripts can access some predefined variables that are summarized in the following table

.. table:: Variables accessible for scripts
 :class: tight-table

 +-----------------------+---------------------------------------------------+---------------------------------------------------+
 | variable              | description                                       | Java type                                         |
 +=======================+===================================================+===================================================+
 | registry              | A preconfigured client for accessing the registry | eu.unicore.client.registry.IRegistryClient        |
 +-----------------------+---------------------------------------------------+---------------------------------------------------+
 | configurationProvider | Security configuration provider (truststore, etc) | de.fzj.unicore.ucc.authn.UCCConfigurationProvider |
 +-----------------------+---------------------------------------------------+---------------------------------------------------+
 | auth                  | REST authentication mechanism                     | eu.unicore.services.rest.client.IAuthCallback     |
 +-----------------------+---------------------------------------------------+---------------------------------------------------+
 | registryURL           | the URL of the registry                           | java.lang.String                                  |
 +-----------------------+---------------------------------------------------+---------------------------------------------------+
 | messageWriter         | for writing messages to the user                  | de.fzj.unicore.ucc.MessageWriter                  |
 +-----------------------+---------------------------------------------------+---------------------------------------------------+
 | commandLine           | the command line                                  | org.apache.commons.cli.CommandLine                |
 +-----------------------+---------------------------------------------------+---------------------------------------------------+
 | properties            | defaults from the user's properties file          | java.util.Properties                              |
 +-----------------------+---------------------------------------------------+---------------------------------------------------+

  
Examples  
~~~~~~~~
  
Some example Groovy scripts can be found in the ``samples/`` directory of the UCC distribution.
