.. _ucc_share:

|share-img| Sharing resources
-----------------------------

.. |share-img| image:: ../../_static/share.png
	:height: 32px
	:align: middle

Accessing UNICORE resources (jobs, storages, ...) is usually only
possible when you *own* the resource or when there are special
server-side policies in place that allow you access.

Starting with server version 7.3, UNICORE supports ACLs on a
*per-service* instance basis. This means, that you can give other users
access to your target systems, jobs, storages,

For example, you might have access to an S3 cloud storage via UNICORE,
and you want to securely share data on this resource. Or, you want to
allow others to check job status, or even allow them to abort jobs.

Note that to access actual files the permissions on file system
level still need to match. Usually this is achieved by using Unix
groups.

Editing ACLs
~~~~~~~~~~~~

The ACLs are managed via the ``share`` command.
Use the basic

.. code:: console

  $ ucc share <URL>

to share the current ACL for the given resource, where *URL* is the full WSRF service URL
of the resource, e.g.

.. code:: console

  $ ucc share https://localhost:8080/DEMO-SITE/rest/core/storages/HOME
 
To add an ACL entry use:

.. code:: console

  $ ucc share ACE1 ACE2 ... <URL> 

where *ACE* is an access control entry expressed in a simple format::

  [read|modify]:[DN|VO|GROUP|UID]:[value]

For example, to give *modify* permission to a user whose UNIX user id on the 
target system is *test*, you would use:

.. code:: console

  $ ucc share modify:UID:test <URL>

To delete entries use the ``-d`` option:

.. code:: console

  $ ucc share -d modify:UID:test <URL>

To delete **all** entries use the ``-b`` option:

.. code:: console

  $ ucc share -b <URL>


Permission levels
~~~~~~~~~~~~~~~~~

The permissions controlled by ACLs are as follows:

 * ``read``: access resource properties
 * ``modify``: perform actions e.g. job submission or creating a file export

Only the **owner** of a resource can edit the ACL or destroy the resource.



