.. _ucc_quickstart:

|start-img| Getting started with UCC
------------------------------------

.. |start-img| image:: ../../_static/start.png
	:height: 32px
	:align: middle

Assuming you have successfully installed UCC, this section
shows how to get started quickly.

.. _ucc_help:

Getting help
~~~~~~~~~~~~

Calling UCC with the ``-h`` option displays the available options. 
To view a list of available commands, use:

.. code:: console

  $ ucc -h

To get help on a specific command, use:

.. code:: console

  $  ucc <command> -h

See also :ref:`ucc_options` for a list of common options.


Connecting
~~~~~~~~~~

First, contact UNICORE and make sure you have access to at least one target system:
  
.. code:: console

  $ ucc connect
  

List available sites
~~~~~~~~~~~~~~~~~~~~

Next, list the sites available to you using: 
  
.. code:: console

  $ ucc list-sites


Running your first job
~~~~~~~~~~~~~~~~~~~~~~

The UCC distribution contains some job examples located in the <UCC_HOME>/samples directory 
that you can run. Let's run the `date.u 
<https://github.com/UNICORE-EU/commandline-client/blob/master/distribution/src/main/samples/date.u>`_ 
sample. The ``-v`` switch enables verbose output, so you can see more details about what is happening.

.. code:: console

  $ ucc run -v <UCC_HOME>/samples/date.u

This command will run *date* on a randomly chosen site, and retrieve the output. 
To target a specific site, use the ``-s`` option to specify the desired system.

.. note:: *Debian distribution on Linux*
  
  If UCC was installed from a DEBIAN file, sample files can be found in 
  ``/usr/share/doc/unicore/ucc/samples`` directory.


.. _list-jobs:

Listing your jobs
~~~~~~~~~~~~~~~~~

To list your jobs along with their status, use the following command:

.. code:: console

  $ ucc list-jobs -l

This will print a list of job URLs with their respective status 
(``RUNNING``, ``SUCCESSFUL``, etc).
  

Accessing Job Files
~~~~~~~~~~~~~~~~~~~

After submitting a job, you can access its output files using various
UCC commands. For example, after running a job, you might want to
inspect the working directory and view the output.

.. code-block:: console
   :emphasize-lines: 2,7,9,12,19
   
   > ucc run date.ucc
    https://mygateway:8080/DEMO-SITE/rest/core/jobs/3QYZPs5HQ3t
    SUCCESSFUL, exit code: 0
    stdout                                                      100%  29 72,1B/s
    stderr
  
   > ucc job-status -l https://mygateway:8080/DEMO-SITE/rest/core/jobs/3QYZPs5HQ3t
    https://mygateway:8080/DEMO-SITE/rest/core/jobs/3QYZPs5HQ3t SUCCESSFUL exit code: 0
    Working directory: https://mygateway:8080/DEMO-SITE/rest/core/storages/3QYZPs5HQ3t-uspace
    Job type: BATCH, queue: 'batch'
   
   > ucc ls https://mygateway:8080/DEMO-SITE/rest/core/storages/3QYZPs5HQ3t-uspace
    /UNICORE_SCRIPT_EXIT_CODE
    /stderr
    /bss_submit_1749042166438
    /stdout
    /UNICORE_Job_1749042166438
   
   > ucc cat https://mygateway:8080/DEMO-SITE/rest/core/storages/3QYZPs5HQ3t-uspace/files/stdout
    Wed Jun 4 13:00:00 UTC 2025