.. _ucc_shell:

|usage-img| The UCC shell
-------------------------

.. |usage-img| image:: ../../_static/usage.png
	:height: 32px
	:align: middle

If you want to run a larger number of UCC commands, the overhead of starting
the Java VM or checking the registry may become annoying. For this scenario, 
UCC offers a ``shell`` that allows the user to enter UCC commands interactively.
  
It is started by
 
.. code:: console

  $ ucc shell <options>

If you want to process a list of commands from a file instead of typing them, you can 
start the shell like this:
  
.. code:: console

  $ ucc shell -f commandsfile

or on Unix you can use the redirection features:

.. code:: console

  $ ucc shell < commandsfile


Changing property settings
~~~~~~~~~~~~~~~~~~~~~~~~~~

To change a property setting in shell mode, you can use the ``set`` command.
Without additional arguments, current properties are listed:

.. code:: console

  ucc> set registry=https://...  output=/tmp  ...

To set one or more properties, add space separated *key=value* strings:

.. code:: console

  ucc> set output=/work registry=https://....


You can also clear a property (set it to null) by using ``unset``:

.. code:: console

  ucc> unset registry

Variables referenced via ``$var_name`` or ``${var_name}`` will be replaced
in commands. You can use this to make commands shorter and more
readable. It's also possible and useful to pre-set certain things in
your preferences file.

For example,

.. code:: console

  ucc> set S1=https://myserver/my_site/rest/core/storages/HOME
  ucc> ls -l $S1

A special variable ``$_`` exists that is set by various commands to
the *last thing* that was created or accessed.

For example,

.. code:: console

  ucc> run -a date.u
  ucc> job-status $_


Running an external command
~~~~~~~~~~~~~~~~~~~~~~~~~~~

You can run an external command via the ``system`` (or simply ``!``) shell
command.  For example,

.. code:: console

  ucc> system vi job.u

or simply

.. code:: console

  ucc> ! cat job.u


Exiting the shell
~~~~~~~~~~~~~~~~~

To exit, type ``exit`` or press :kbd:`Control-D`.
