.. _ucc_faq:

|faq-img| Frequently asked questions
------------------------------------

.. |faq-img| image:: ../../_static/FAQ.png
	:height: 32px
	:align: middle

Configuration
~~~~~~~~~~~~~

|:thinking:| **Do I really have to store my password in the preferences file? Isn't 
this insecure?**
   
	Putting the password in a file or giving it as a commandline parameter can be 
	considered insecure. The file could be read by others, and the commandline parameters may be 
	visible in for example in the output of the ``ps`` command. 
	Thus, UCC will simply ask for the password in case you did not specify it.

|:thinking:| **How can I enable more detailed logging?**

	UCC uses `Log4j 2 <https://logging.apache.org/log4j/2.x/manual/configuration.html>`_, 
	by default the configuration is done in ``<UCC_HOME>/conf/logging.properties``. You can edit 
	this file and increase the logging levels, choose to log to a file or to the console, etc.


Usage
~~~~~

|:thinking:| **Can I use multiple registries with UCC?**
 
	Yes. Simply use a comma-separated list of URLs for the ``-r`` option. 
	However, you may only use a single authentication setup, so all registries
	(and sites listed in them) must accept the same security credentials.


|:thinking:| **Can I upload and execute my own executable?**
 
	Yes. Check :ref:`ucc_jobs`.


|:thinking:| **Can I use UCC to list the contents of the registry?**
 
	Using the :ref:`rest command <rest-command>` this is very easy. For example,

	.. code:: console

		$ ucc rest get https://localhost:8080/DEMO-SITE/rest/registries/default_registry

	will list the content of the registry.

