.. table:: JSON IDB Application
 :width: 100 
 :widths: 30 15 35 15 
 :class: tight-table

 +---------------------+---------------+----------------------------------+-------------------+
 |Tag                  |Type           |Description                       |Optional\/mandatory|
 +=====================+===============+==================================+===================+
 |Name                 |String         |Application name                  |Mandatory          |
 +---------------------+---------------+----------------------------------+-------------------+
 |Version              |String         |Application version               |Mandatory          |
 +---------------------+---------------+----------------------------------+-------------------+
 |Description          |String         |Application description           |Optional           |
 +---------------------+---------------+----------------------------------+-------------------+
 |Executable           |String         |Executable                        |Mandatory          |
 +---------------------+---------------+----------------------------------+-------------------+
 |Arguments            |List of        |Command line arguments            |Optional           |
 |                     |strings        |                                  |                   |
 +---------------------+---------------+----------------------------------+-------------------+
 |Environment          |Map of strings |Environment values                |Optional           |
 +---------------------+---------------+----------------------------------+-------------------+
 |PreCommand           |String         |Pre-processing executed on the    |Optional           |
 |                     |               |login node                        |                   |
 +---------------------+---------------+----------------------------------+-------------------+
 |PostCommand          |String         |Post-processing executed on the   |Optional           |
 |                     |               |login node                        |                   |
 +---------------------+---------------+----------------------------------+-------------------+
 |Prologue             |String         |Pre-processing in the batch script|Optional           |
 +---------------------+---------------+----------------------------------+-------------------+
 |Epiloge              |String         |Post-processing in the batch      |Optional           |
 |                     |               |script                            |                   |
 +---------------------+---------------+----------------------------------+-------------------+
 |Parameters           |Map            |Metadata for application          |Optional           |
 |                     |               |arguments \/ parameters           |                   |
 +---------------------+---------------+----------------------------------+-------------------+
 |Resources            |Map            |Application-specific resource     |Optional           |
 |                     |               |requests                          |                   |
 +---------------------+---------------+----------------------------------+-------------------+
 |RunOnLoginNode       |"true"\/"false"|Run job on login node             |Optional,          |
 |                     |               |                                  |default=false      |
 +---------------------+---------------+----------------------------------+-------------------+
 |IgnoreNonZeroExitCode|"true"\/"false"|Don't fail the job if app exits   |Optional,          |
 |                     |               |with non-zero exit code           |default=true       |
 +---------------------+---------------+----------------------------------+-------------------+
