.. table:: UNICORE/X configuration files
 :width: 100 
 :widths: 30 40 30 
 :class: tight-table

 +----------------------+--------------------------------------+--------------------------+
 |config file           |usage                                 |dynamically reloaded      |
 +======================+======================================+==========================+
 |startup.properties    |Java process settings (e.g. memory),  |no                        |
 |                      |lib\/log\/conf directories            |                          |
 +----------------------+--------------------------------------+--------------------------+
 |logging.properties    |Logging levels, logfiles and their    |yes                       |
 |                      |properties                            |                          |
 +----------------------+--------------------------------------+--------------------------+
 |uas.config            |Main server config file. Defines      |no                        |
 |                      |features, storages, AuthN\/AuthZ,     |                          |
 |                      |AIPs\/PDPs                            |                          |
 +----------------------+--------------------------------------+--------------------------+
 |container.properties  |Server address, SSL settings, Web     |no                        |
 |                      |server settings                       |                          |
 +----------------------+--------------------------------------+--------------------------+
 |xnjs.properties       |Backend properties for the UNICORE TSI|no                        |
 +----------------------+--------------------------------------+--------------------------+
 |simpleidb             |Backend, installed applications,      |yes                       |
 |                      |resources                             |                          |
 +----------------------+--------------------------------------+--------------------------+
 |simpleuudb            |Maps user DNs to local attributes     |yes                       |
 |                      |(optional)                            |                          |
 +----------------------+--------------------------------------+--------------------------+
 |rest-users.txt        |Usernames\/passwords for REST         |yes                       |
 |                      |authentication (optional)             |                          |
 +----------------------+--------------------------------------+--------------------------+
 |xacml2Policies\/\*.xml|Access control policy for securing the|yes, via xacml2.config (do|
 |                      |web services                          |touch xacml2.config to    |
 |                      |                                      |trigger)                  |
 +----------------------+--------------------------------------+--------------------------+
 |xacml2.config         |Configure the XACML2 access control   |yes                       |
 |                      |component                             |                          |
 +----------------------+--------------------------------------+--------------------------+
 |vo.config             |Configure the use of Unity as an      |no                        |
 |                      |attribute source (optional)           |                          |
 +----------------------+--------------------------------------+--------------------------+
