.. table:: 
 :width: 100 
 :widths: 25 20 15 40 
 :class: tight-table

 +------------------------+------------------+-------------+---------------------------------------+
 |Property name           |Type              |Default value|Description                            |
 |                        |                  |             |                                       |
 |                        |                  |\/ mandatory |                                       |
 +========================+==================+=============+=======================================+
 |persistence.cache.      |[true, false] can |true         |Enable caching.                        |
 |                        |                  |             |                                       |
 |enable[.\*]             |have subkeys      |             |                                       |
 +------------------------+------------------+-------------+---------------------------------------+
 |persistence.cache.      |integer number can|10           |Maximum number of elements in the      |
 |                        |                  |             |                                       |
 |maxSize[.\*]            |have subkeys      |             |cache (default: 10).                   |
 +------------------------+------------------+-------------+---------------------------------------+
 |persistence.class[.\*]  |string can have   |de.fzj.      |The persistence implementation class,  |
 |                        |                  |             |                                       |
 |                        |subkeys           |unicore.     |which controls with DB backend is used.|
 |                        |                  |             |                                       |
 |                        |                  |persist.impl.|                                       |
 |                        |                  |             |                                       |
 |                        |                  |H2Persist    |                                       |
 +------------------------+------------------+-------------+---------------------------------------+
 |persistence.cluster.    |string can have   |\-           |Clustering configuration file.         |
 |                        |                  |             |                                       |
 |config[.\*]             |subkeys           |             |                                       |
 +------------------------+------------------+-------------+---------------------------------------+
 |persistence.cluster.    |[true, false] can |false        |Enable clustering mode.                |
 |                        |                  |             |                                       |
 |enable[.\*]             |have subkeys      |             |                                       |
 +------------------------+------------------+-------------+---------------------------------------+
 |persistence.config      |filesystem path   |\-           |Allows to specify a separate           |
 |                        |                  |             |                                       |
 |                        |                  |             |properties file containing the         |
 |                        |                  |             |                                       |
 |                        |                  |             |persistence configuration.             |
 +------------------------+------------------+-------------+---------------------------------------+
 |persistence.database[.  |string can have   |\-           |The name of the database to connect to |
 |                        |                  |             |                                       |
 |\*]                     |subkeys           |             |(e.g. when using MySQL).               |
 +------------------------+------------------+-------------+---------------------------------------+
 |persistence.directory[. |string can have   |\-           |The directory for storing data         |
 |                        |                  |             |                                       |
 |\*]                     |subkeys           |             |(embedded DBs).                        |
 +------------------------+------------------+-------------+---------------------------------------+
 |persistence.driver[.\*] |string can have   |\-           |The database driver. If not set, the   |
 |                        |                  |             |                                       |
 |                        |subkeys           |             |default one for the chosen DB backend  |
 |                        |                  |             |                                       |
 |                        |                  |             |is used.                               |
 +------------------------+------------------+-------------+---------------------------------------+
 |persistence.h2.cache\_  |integer number can|1024         |(H2) Cache size.                       |
 |                        |                  |             |                                       |
 |size[.\*]               |have subkeys      |             |                                       |
 +------------------------+------------------+-------------+---------------------------------------+
 |persistence.h2.options[.|string can have   |\-           |(H2) Further options separated by ;.   |
 |                        |                  |             |                                       |
 |\*]                     |subkeys           |             |                                       |
 +------------------------+------------------+-------------+---------------------------------------+
 |persistence.h2.server\_ |[true, false] can |false        |(H2) Connect to a H2 server.           |
 |                        |                  |             |                                       |
 |mode[.\*]               |have subkeys      |             |                                       |
 +------------------------+------------------+-------------+---------------------------------------+
 |persistence.host[.\*]   |string can have   |localhost    |The database host.                     |
 |                        |                  |             |                                       |
 |                        |subkeys           |             |                                       |
 +------------------------+------------------+-------------+---------------------------------------+
 |persistence.max\_       |integer number can|1            |Connection pool maximum size.          |
 |                        |                  |             |                                       |
 |connections[.\*]        |have subkeys      |             |                                       |
 +------------------------+------------------+-------------+---------------------------------------+
 |persistence.mysql.      |string can have   |MyISAM       |(MySQL) Table type (engine) to use.    |
 |                        |                  |             |                                       |
 |tabletype[.\*]          |subkeys           |             |                                       |
 +------------------------+------------------+-------------+---------------------------------------+
 |persistence.mysql.      |string can have   |UTC          |(MySQL) Server timezone.               |
 |                        |                  |             |                                       |
 |timezone[.\*]           |subkeys           |             |                                       |
 +------------------------+------------------+-------------+---------------------------------------+
 |persistence.mysql.      |[true, false] can |false        |(MySQL) Connect using SSL.             |
 |                        |                  |             |                                       |
 |useSSL[.\*]             |have subkeys      |             |                                       |
 +------------------------+------------------+-------------+---------------------------------------+
 |persistence.password[.  |string can have   |empty string |The database password.                 |
 |                        |                  |             |                                       |
 |\*]                     |subkeys           |             |                                       |
 +------------------------+------------------+-------------+---------------------------------------+
 |persistence.pool\_      |integer number can|3600         |Connection pool timeout when trying to |
 |                        |                  |             |                                       |
 |timeout[.\*]            |have subkeys      |             |get a connection.                      |
 +------------------------+------------------+-------------+---------------------------------------+
 |persistence.port[.\*]   |integer number can|3306         |The database port.                     |
 |                        |                  |             |                                       |
 |                        |have subkeys      |             |                                       |
 +------------------------+------------------+-------------+---------------------------------------+
 |persistence.user[.\*]   |string can have   |sa           |The database username.                 |
 |                        |                  |             |                                       |
 |                        |subkeys           |             |                                       |
 +------------------------+------------------+-------------+---------------------------------------+
