.. table:: 
 :width: 100 
 :widths: 25 20 15 40 
 :class: tight-table

 +----------------------+------------------+-------------+---------------------------------------+
 |Property name         |Type              |Default value|Description                            |
 |                      |                  |\/ mandatory |                                       |
 +======================+==================+=============+=======================================+
 |container.client.     |[true, false]     |true         |Controls whether signing of key web    |
 |digitalSigningEnabled |                  |             |service requests should be performed.  |
 +----------------------+------------------+-------------+---------------------------------------+
 |container.client.     |[true, false]     |false        |Whether HTTP basic authentication      |
 |httpAuthnEnabled      |                  |             |should be used.                        |
 +----------------------+------------------+-------------+---------------------------------------+
 |container.client.     |string            |empty string |Password for use with HTTP basic       |
 |httpPassword          |                  |             |authentication (if enabled).           |
 +----------------------+------------------+-------------+---------------------------------------+
 |container.client.     |string            |empty string |Username for use with HTTP basic       |
 |httpUser              |                  |             |authentication (if enabled).           |
 +----------------------+------------------+-------------+---------------------------------------+
 |container.client.     |string            |empty string |Space separated list of additional     |
 |inHandlers            |                  |             |handler class names for handling       |
 |                      |                  |             |incoming WS messages                   |
 +----------------------+------------------+-------------+---------------------------------------+
 |container.client.     |integer number    |3            |Controls how many times the client     |
 |maxWsCallRetries      |                  |             |should try to call a failing web       |
 |                      |                  |             |service. Note that only the transient  |
 |                      |                  |             |failure reasons cause the retry. Note  |
 |                      |                  |             |that value of 0 enables unlimited      |
 |                      |                  |             |number of retries, while value of 1    |
 |                      |                  |             |means that only one call is tried.     |
 +----------------------+------------------+-------------+---------------------------------------+
 |container.client.     |[true, false]     |false        |Controls whether messages should be    |
 |messageLogging        |                  |             |logged (at INFO level).                |
 +----------------------+------------------+-------------+---------------------------------------+
 |container.client.     |string            |empty string |Space separated list of additional     |
 |outHandlers           |                  |             |handler class names for handling       |
 |                      |                  |             |outgoing WS messages                   |
 +----------------------+------------------+-------------+---------------------------------------+
 |container.client.     |[true, false]     |true         |Controls whether security sessions     |
 |securitySessions      |                  |             |should be enabled.                     |
 +----------------------+------------------+-------------+---------------------------------------+
 |container.client.     |[NONE, WARN, FAIL]|WARN         |Controls whether server's hostname     |
 |serverHostnameChecking|                  |             |should be checked for matching its     |
 |                      |                  |             |certificate subject. This verification |
 |                      |                  |             |prevents man\-in\-the\-middle attacks. |
 |                      |                  |             |If enabled WARN will only print        |
 |                      |                  |             |warning in log, FAIL will close the    |
 |                      |                  |             |connection.                            |
 +----------------------+------------------+-------------+---------------------------------------+
 |container.client.     |[true, false]     |true         |Controls whether SSL authentication of |
 |sslAuthnEnabled       |                  |             |the client should be performed.        |
 +----------------------+------------------+-------------+---------------------------------------+
 |container.client.     |integer number    |10000        |Amount of milliseconds to wait before  |
 |wsCallRetryDelay      |                  |             |retry of a failed web service call.    |
 +----------------------+------------------+-------------+---------------------------------------+
 |container.client.http.|[true, false]     |true         |If set to false, then the client will  |
 |allow\-chunking       |                  |             |not use HTTP 1.1 data chunking.        |
 +----------------------+------------------+-------------+---------------------------------------+
 |container.client.http.|[true, false]     |false        |If set to true then the client will    |
 |connection\-close     |                  |             |send connection close header, so the   |
 |                      |                  |             |server will close the socket.          |
 +----------------------+------------------+-------------+---------------------------------------+
 |container.client.http.|integer number    |20000        |Timeout for the connection             |
 |connection.timeout    |                  |             |establishing (ms)                      |
 +----------------------+------------------+-------------+---------------------------------------+
 |container.client.http.|integer number    |6            |How many connections per host can be   |
 |maxPerRoute           |                  |             |made. Note: this is a limit for a      |
 |                      |                  |             |single client object instance.         |
 +----------------------+------------------+-------------+---------------------------------------+
 |container.client.http.|integer number    |3            |Maximum number of allowed HTTP         |
 |maxRedirects          |                  |             |redirects.                             |
 +----------------------+------------------+-------------+---------------------------------------+
 |container.client.http.|integer number    |20           |How many connections in total can be   |
 |maxTotal              |                  |             |made. Note: this is a limit for a      |
 |                      |                  |             |single client object instance.         |
 +----------------------+------------------+-------------+---------------------------------------+
 |container.client.http.|integer number    |0            |Socket timeout (ms)                    |
 |socket.timeout        |                  |             |                                       |
 +----------------------+------------------+-------------+---------------------------------------+
 |container.client.http.|string            |\-           |Space (single) separated list of hosts,|
 |nonProxyHosts         |                  |             |for which the HTTP proxy should not be |
 |                      |                  |             |used.                                  |
 +----------------------+------------------+-------------+---------------------------------------+
 |container.client.http.|string            |\-           |Relevant only when using HTTP proxy:   |
 |proxy.password        |                  |             |defines password for authentication to |
 |                      |                  |             |the proxy.                             |
 +----------------------+------------------+-------------+---------------------------------------+
 |container.client.http.|string            |\-           |Relevant only when using HTTP proxy:   |
 |proxy.user            |                  |             |defines username for authentication to |
 |                      |                  |             |the proxy.                             |
 +----------------------+------------------+-------------+---------------------------------------+
 |container.client.http.|string            |\-           |If set then the HTTP proxy will be     |
 |proxyHost             |                  |             |used, with this hostname.              |
 +----------------------+------------------+-------------+---------------------------------------+
 |container.client.http.|integer number    |\-           |HTTP proxy port. If not defined then   |
 |proxyPort             |                  |             |system property is consulted, and as a |
 |                      |                  |             |final fallback 80 is used.             |
 +----------------------+------------------+-------------+---------------------------------------+
 |container.client.http.|string            |HTTP         |HTTP proxy type: HTTP or SOCKS.        |
 |proxyType             |                  |             |                                       |
 +----------------------+------------------+-------------+---------------------------------------+
