.. table:: 
 :width: 100 
 :widths: 20 20 20 40 
 :class: tight-table

 +--------------------+-------------------+--------------------------+---------------------------------------+
 |Property name       |Type               |Default value \/          |Description                            |
 |                    |                   |                          |                                       |
 |                    |                   |mandatory                 |                                       |
 +====================+===================+==========================+=======================================+
 |coreServices.       |[true, false]      |true                      |Whether the allow the user to set the  |
 |                    |                   |                          |                                       |
 |targetsystem.       |                   |                          |storage base directory when creating   |
 |                    |                   |                          |                                       |
 |storage.N.          |                   |                          |the storage via the StorageFactory.    |
 |                    |                   |                          |                                       |
 |allowUserDefinedPath|                   |                          |                                       |
 +--------------------+-------------------+--------------------------+---------------------------------------+
 |coreServices.       |[true, false]      |true                      |Whether the existence of the base      |
 |                    |                   |                          |                                       |
 |targetsystem.       |                   |                          |directory should be checked when       |
 |                    |                   |                          |                                       |
 |storage.N.          |                   |                          |creating the storage.                  |
 |                    |                   |                          |                                       |
 |checkExistence      |                   |                          |                                       |
 +--------------------+-------------------+--------------------------+---------------------------------------+
 |coreServices.       |Class extending de.|\-                        |Storage implementation class used (and |
 |                    |                   |                          |                                       |
 |targetsystem.       |fzj.unicore.uas.   |                          |mandatory) in case of the CUSTOM type. |
 |                    |                   |                          |                                       |
 |storage.N.class     |impl.sms.          |                          |                                       |
 |                    |                   |                          |                                       |
 |                    |SMSBaseImpl        |                          |                                       |
 +--------------------+-------------------+--------------------------+---------------------------------------+
 |coreServices.       |[true, false]      |false                     |Whether files of the storage should be |
 |                    |                   |                          |                                       |
 |targetsystem.       |                   |                          |removed when the storage is destroyed. |
 |                    |                   |                          |                                       |
 |storage.N.cleanup   |                   |                          |This is mostly useful for storage      |
 |                    |                   |                          |                                       |
 |                    |                   |                          |factories. (runtime updateable)        |
 +--------------------+-------------------+--------------------------+---------------------------------------+
 |coreServices.       |integer number     |77                        |Default (initial) umask for files in   |
 |                    |                   |                          |                                       |
 |targetsystem.       |                   |                          |the storage. Must be an octal number.  |
 |                    |                   |                          |                                       |
 |storage.N.          |                   |                          |Note that this property is not         |
 |                    |                   |                          |                                       |
 |defaultUmask        |                   |                          |updateable at runtime for normal       |
 |                    |                   |                          |                                       |
 |                    |                   |                          |storages as it wouldn't have sense (it |
 |                    |                   |                          |                                       |
 |                    |                   |                          |is the initial umask by definition).   |
 |                    |                   |                          |                                       |
 |                    |                   |                          |However in case of storage factory it  |
 |                    |                   |                          |                                       |
 |                    |                   |                          |is, i.e. after the property change,    |
 |                    |                   |                          |                                       |
 |                    |                   |                          |the SMSes created by the factory will  |
 |                    |                   |                          |                                       |
 |                    |                   |                          |use the new umask as the initial one.  |
 |                    |                   |                          |                                       |
 |                    |                   |                          |At runtime the SMS umask can be        |
 |                    |                   |                          |                                       |
 |                    |                   |                          |changed by the clients (if are         |
 |                    |                   |                          |                                       |
 |                    |                   |                          |authorized to do so).                  |
 +--------------------+-------------------+--------------------------+---------------------------------------+
 |coreServices.       |string             |Filesystem                |Description of the storage. It will be |
 |                    |                   |                          |                                       |
 |targetsystem.       |                   |                          |presented to the users. (runtime       |
 |                    |                   |                          |                                       |
 |storage.N.          |                   |                          |updateable)                            |
 |                    |                   |                          |                                       |
 |description         |                   |                          |                                       |
 +--------------------+-------------------+--------------------------+---------------------------------------+
 |coreServices.       |[true, false]      |false                     |Whether the metadata service should be |
 |                    |                   |                          |                                       |
 |targetsystem.       |                   |                          |disabled for this storage.             |
 |                    |                   |                          |                                       |
 |storage.N.          |                   |                          |                                       |
 |                    |                   |                          |                                       |
 |disableMetadata     |                   |                          |                                       |
 +--------------------+-------------------+--------------------------+---------------------------------------+
 |coreServices.       |[true, false]      |false                     |Whether the triggering feature should  |
 |                    |                   |                          |                                       |
 |targetsystem.       |                   |                          |be enabled for this storage.           |
 |                    |                   |                          |                                       |
 |storage.N.          |                   |                          |                                       |
 |                    |                   |                          |                                       |
 |enableTrigger       |                   |                          |                                       |
 +--------------------+-------------------+--------------------------+---------------------------------------+
 |coreServices.       |[true, false]      |false                     |If set to true then this SMS will      |
 |                    |                   |                          |                                       |
 |targetsystem.       |                   |                          |filter returned files in response of   |
 |                    |                   |                          |                                       |
 |storage.N.          |                   |                          |the ListDirectory command: only files  |
 |                    |                   |                          |                                       |
 |filterFiles         |                   |                          |owned or accessible by the caller will |
 |                    |                   |                          |                                       |
 |                    |                   |                          |be returned. (runtime updateable)      |
 +--------------------+-------------------+--------------------------+---------------------------------------+
 |coreServices.       |Class extending de.|de.fzj.unicore.uas.       |(Very) advanced setting, providing     |
 |                    |                   |                          |                                       |
 |targetsystem.       |fzj.unicore.uas.   |impl.sms.                 |information about storages produced by |
 |                    |                   |                          |                                       |
 |storage.N.          |impl.sms.          |DefaultStorageInfoProvider|the SMS factory.                       |
 |                    |                   |                          |                                       |
 |infoProviderClass   |StorageInfoProvider|                          |                                       |
 +--------------------+-------------------+--------------------------+---------------------------------------+
 |coreServices.       |string             |\-                        |Storage name. If not set then the      |
 |                    |                   |                          |                                       |
 |targetsystem.       |                   |                          |internal unique identifier is used.    |
 |                    |                   |                          |                                       |
 |storage.N.name      |                   |                          |                                       |
 +--------------------+-------------------+--------------------------+---------------------------------------+
 |coreServices.       |string             |\-                        |Denotes the storage base path.         |
 |                    |                   |                          |                                       |
 |targetsystem.       |                   |                          |                                       |
 |                    |                   |                          |                                       |
 |storage.N.path      |                   |                          |                                       |
 +--------------------+-------------------+--------------------------+---------------------------------------+
 |coreServices.       |string             |\-                        |(DEPRECATED, ignored) (runtime         |
 |                    |                   |                          |                                       |
 |targetsystem.       |                   |                          |updateable)                            |
 |                    |                   |                          |                                       |
 |storage.N.protocols |                   |                          |                                       |
 +--------------------+-------------------+--------------------------+---------------------------------------+
 |coreServices.       |string can have    |\-                        |Useful for CUSTOM storage types:       |
 |                    |                   |                          |                                       |
 |targetsystem.       |subkeys            |                          |allows to set additional settings (if  |
 |                    |                   |                          |                                       |
 |storage.N.settings. |                   |                          |needed) by such storages. Please refer |
 |                    |                   |                          |                                       |
 |[.\*]               |                   |                          |to documentation of a particular       |
 |                    |                   |                          |                                       |
 |                    |                   |                          |custom storage type for details. Note  |
 |                    |                   |                          |                                       |
 |                    |                   |                          |that while in general updates of the   |
 |                    |                   |                          |                                       |
 |                    |                   |                          |properties at runtime are propagated   |
 |                    |                   |                          |                                       |
 |                    |                   |                          |to the chosen implementation, it is up |
 |                    |                   |                          |                                       |
 |                    |                   |                          |to it to use the updated values or     |
 |                    |                   |                          |                                       |
 |                    |                   |                          |ignore changes. (runtime updateable)   |
 +--------------------+-------------------+--------------------------+---------------------------------------+
 |coreServices.       |string             |\-                        |For data triggering on shared storages,|
 |                    |                   |                          |                                       |
 |targetsystem.       |                   |                          |use this user ID for the controlling   |
 |                    |                   |                          |                                       |
 |storage.N.          |                   |                          |process.                               |
 |                    |                   |                          |                                       |
 |triggerUserID       |                   |                          |                                       |
 +--------------------+-------------------+--------------------------+---------------------------------------+
 |coreServices.       |string             |\-                        |Storage type. FIXEDPATH: mapped to a   |
 |                    |                   |                          |                                       |
 |targetsystem.       |                   |                          |fixed directory, VARIABLE: resolved    |
 |                    |                   |                          |                                       |
 |storage.N.type      |                   |                          |using an environmental variable lookup,|
 |                    |                   |                          |                                       |
 |                    |                   |                          |CUSTOM: specified class is used.       |
 +--------------------+-------------------+--------------------------+---------------------------------------+
 |coreServices.       |string             |\-                        |(DEPRECATED, use path instead)         |
 |                    |                   |                          |                                       |
 |targetsystem.       |                   |                          |                                       |
 |                    |                   |                          |                                       |
 |storage.N.workdir   |                   |                          |                                       |
 +--------------------+-------------------+--------------------------+---------------------------------------+
