.. table:: 
 :width: 100 
 :widths: 20 15 25 40 
 :class: tight-table

 +-----------------+-----------+---------------------+-------------------------------------+
 |Property name    |Type       |Default value \/     |Description                          |
 |                 |           |mandatory            |                                     |
 +=================+===========+=====================+=====================================+
 |xuudb.db.dialect |[h2, mysql]|h2                   |Database SQL dialect. Must match the |
 |                 |           |                     |selected driver, however sometimes   |
 |                 |           |                     |more then one driver can be available|
 |                 |           |                     |for a dialect.                       |
 +-----------------+-----------+---------------------+-------------------------------------+
 |xuudb.db.driver  |Class      |org.h2.Driver        |Database driver class name. This     |
 |                 |extending  |                     |property is optional \- if not set,  |
 |                 |java.sql.  |                     |then a default driver for the chosen |
 |                 |Driver     |                     |database type is used.               |
 +-----------------+-----------+---------------------+-------------------------------------+
 |xuudb.db.jdbcUrl |string     |\jdbc:h2:data\/xuudb2|Database JDBC URL.                   |
 +-----------------+-----------+---------------------+-------------------------------------+
 |xuudb.db.password|string     |empty string         |Database password.                   |
 +-----------------+-----------+---------------------+-------------------------------------+
 |xuudb.db.username|string     |sa                   |Database username.                   |
 +-----------------+-----------+---------------------+-------------------------------------+
