.. _user-docs:


|user-img| User Documentation
=============================

.. |user-img| image:: _static/user.png
	:height: 32px
	:align: middle

- :ref:`ucc` - a full featured commandline client for UNICORE
- :ref:`rest-api` - REST-API for the :ref:`UNICORE/X server <unicorex>` (job submission and management, 
  data access and data transfer) and the :ref:`Workflow server <workflow>` (workflow submission 
  and management)
- :ref:`job-description` - the job description format 
- :ref:`workflow-description` - the workflow description language 

.. toctree::
	:maxdepth: 3
	:caption: User Documentation
	:hidden:

	user-docs/ucc/index
	user-docs/rest-api/index
	user-docs/rest-api/job-description/index
	user-docs/rest-api/workflow-description/index
