.. _user-docs:


User Documentation
==================

- :ref:`ucc` - a full featured commandline client for UNICORE.
- :ref:`rest-api` - REST-API for job submission and management, 
  data access and transfer, workflow submission and management

  - :ref:`job-description` - the job description format 
  - :ref:`workflow-description` - the workflow description language 

.. toctree::
	:maxdepth: 5
	:caption: User Documentation
	:hidden:

	user-docs/ucc/index
	user-docs/rest-api/index
	user-docs/rest-api/job-description/index
	user-docs/rest-api/workflow-description/index



