.. _user-docs:


User Documentation
==================

- |info-img| :ref:`user-docs-introduction`
	Introduction for UNICORE users.

- |usage-img| :ref:`ucc`
	A full featured commandline client for UNICORE.

- |api-img| :ref:`rest-api`
	REST-API for the :ref:`UNICORE/X server <unicorex>` (job submission and management, 
	data access and data transfer) and the :ref:`Workflow server <workflow>` (workflow submission 
	and management).

- |job-desc-img| :ref:`job-description`
	The job description format that allows you to specify the application or executable you want 
	to run, arguments and environment settings, any files to stage in from remote servers and any 
	result files to stage out.

- |workflow-img| :ref:`workflow-description`
	The workflow description language that is supported by the :ref:`Workflow engine <workflow>`. 

- |data-triggered-img| :ref:`data-triggered`
	Reference for the data-triggered processing in UNICORE/X.

- |uftp-img| :ref:`UFTP Client <uftp-docs:uftp-client>`
	The UNICORE File Transfer Client for high performance data transfer.

.. |info-img| image:: _static/user-guide.png
	:height: 32px
	:align: middle

.. |usage-img| image:: _static/usage.png
	:height: 24px
	:align: middle

.. |api-img| image:: _static/api.png
	:height: 24px
	:align: middle

.. |job-desc-img| image:: _static/job-desc.png
	:height: 24px
	:align: middle

.. |workflow-img| image:: _static/workflow.png
	:height: 32px
	:align: middle


.. |data-triggered-img| image:: _static/move-files.png
	:height: 24px
	:align: middle

.. |uftp-img| image:: _static/uftp.png
	:height: 24px
	:align: middle

.. toctree::
	:maxdepth: 3
	:caption: User Documentation
	:hidden:

	user-docs/user-docs-introduction
	user-docs/ucc/index
	user-docs/rest-api/index
	user-docs/rest-api/job-description/index
	user-docs/rest-api/workflow-description/index
	user-docs/data-triggered-processing
	UFTP Client -> <https://uftp-docs.readthedocs.io/en/latest/user-docs/uftp-client>
	
