.. table:: 
 :width: 100 
 :widths: 20 20 20 40 
 :class: tight-table

 +------------------------------+-------------+----------------+---------------------------------------+
 |Property name                 |Type         |Default value \/|Description                            |
 |                              |             |                |                                       |
 |                              |             |mandatory       |                                       |
 +==============================+=============+================+=======================================+
 |workflow.                     |[true, false]|true            |Whether to remove child jobs when the  |
 |                              |             |                |                                       |
 |cleanupJobs                   |             |                |workflow is destroyed.                 |
 +------------------------------+-------------+----------------+---------------------------------------+
 |workflow.                     |[true, false]|false           |Whether to cleanup the workflow        |
 |                              |             |                |                                       |
 |cleanupStorage                |             |                |storage when the workflow is destroyed.|
 +------------------------------+-------------+----------------+---------------------------------------+
 |workflow.                     |integer \>= 1|100             |Maximum number of concurrent for\-each |
 |                              |             |                |                                       |
 |forEachMaxConcurrentActivities|             |                |iterations.                            |
 +------------------------------+-------------+----------------+---------------------------------------+
 |workflow.                     |integer \>= 1|1000            |Maximum number of workflow activities  |
 |                              |             |                |                                       |
 |maxActivitiesPerGroup         |             |                |per activity group.                    |
 +------------------------------+-------------+----------------+---------------------------------------+
 |workflow.                     |integer \>= 1|600             |Interval in seconds for (slow) polling |
 |                              |             |                |                                       |
 |pollingInterval               |             |                |of job states.                         |
 +------------------------------+-------------+----------------+---------------------------------------+
 |workflow.                     |[true, false]|false           |Whether to disable automatic re\-      |
 |                              |             |                |                                       |
 |resubmitDisable               |             |                |submission of failed jobs.             |
 +------------------------------+-------------+----------------+---------------------------------------+
 |workflow.                     |integer \>= 1|3               |Maximum number of re\-submissions of   |
 |                              |             |                |                                       |
 |resubmitLimit                 |             |                |failed jobs.                           |
 +------------------------------+-------------+----------------+---------------------------------------+
 |workflow.                     |string       |n\/a            |(deprecated)                           |
 |                              |             |                |                                       |
 |xnjsConfiguration             |             |                |                                       |
 +------------------------------+-------------+----------------+---------------------------------------+
