
UNICORE Container (USE)
=======================

UNICORE Services Environment (USE) is a hosting environment used by most of the UNICORE servers. 
It provides a common security, persistence and Web-Services infrastructure. The following sections 
describe the USE functionality. It can be assumed that the same functionality is available also 
for other USE based servers.   

.. include:: use-configuration.rest

.. include:: use-admin.rest

.. include:: use-persistence.rest

.. include:: use-security_concepts.rest

.. include:: use-attribute-sources.rest

.. include:: use-vo.rest

.. include:: use-authorization.rest

.. include:: use-policies.rest

.. include:: use-rest.rest