.. _use_pdp:

|pdp-img| Authorization back-end (PDP) guide
--------------------------------------------

.. |pdp-img| image:: ../../_static/pdp.png
	:height: 32px
	:align: middle

The authorization process in UNICORE/X requires that nearly all operations 
must be authorized prior to execution (exceptions may be safely ignored).
 
UNICORE allows to choose which authorization back-end is used. The module which
is responsible for this operation is called **P**\ olicy **D**\ ecision **P**\ oint (PDP). 
You can choose one among already available PDP modules or even develop your own engine.

Local PDPs use a set of policy files to reach an authorisation decision, remote PDPs query
a remote service. Local UNICORE PDPs use the XACML language to express the authorization policy. The XACML policy
language is introduced in the :ref:`use_policies`.
You can also review this guide if you want to have a deeper understanding of the authorization 
process. 

 
Basic configuration  
~~~~~~~~~~~~~~~~~~~

.. note::
 The full list of options related to PDP is available :ref:`here <use-secref>`.


There are three options which are relevant to all PDPs:
  
- ``container.security.accesscontrol`` (values: ``true`` or ``false``) This boolean property can be used 
  to completely turn off the authorization. This guide makes sense only if this option is set to ``true``.
  Except for test scenarios this should never be switched off, otherwise every user can in principle 
  access all resources on the server.

- ``container.security.accesscontrol.pdp`` (value: *full class name*) This property is used to choose
  which PDP module is being used. If not set the DefaultPDP will be used.

- ``container.security.accesscontrol.pdpConfig`` (value: *file path*) This property provides a location
  of a configuration file of the selected PDP.  


Available PDP modules
~~~~~~~~~~~~~~~~~~~~~
.. note::
 This PDP is available since UNICORE 11.

DefaultPDP
^^^^^^^^^^

This PDP is used when the pdp class is not explicitely configured, or if the 
pdp class is set to ``eu.unicore.services.security.pdp.DefaultPDP``.

This PDP uses hard-coded rules, which are defined in the service code itself and cannot be
modified or extended by the administrator.

The PDP implements the "normal" UNICORE behaviour:

- role "admin" can do anything
- role "banned" can do nothing
- the owner of a service instance has full access
- access is allowed if the service instance ACL permits it
- role "user" can list public services, use public endpoints (e.g. for job submission)

In addition, services can define additional access rules.

XACML 2.0 PDP
^^^^^^^^^^^^^

This PDP allows more detailed (and most importantly, non-standard) access control policies.
For almost all use cases, the DefaultPDP is fine.

The implementation class of this module is: ``eu.unicore.services.pdp.local.LocalHerasafPDP`` so
to enable this module use the following configuration in ``main.config``::

 container.security.accesscontrol.pdpConfig=<CONFIG_DIR>/xacml2.conf
 container.security.accesscontrol.pdp=eu.unicore.services.pdp.local.LocalHerasafPDP

The configuration file content is very simplistic as it is enough to define only few options::

	# The directory where XACML 2.0 policy files are stored 
	localpdp.directory=conf/xacml2Policies

	# Wildcard expression to select actual policy files from the directory defined above  
	localpdp.filesWildcard=*.xml

	# Combining algorithm for the policies. You can use the full XACML id or its last part. 
	localpdp.combiningAlg=first-applicable

The policies from the ``localpdp.directory`` are always evaluated in alphabetical order,
so it is good to name files with a number. By default, the first-applicable combining algorithm is
used and UNICORE policy is stored in two files: ``01coreServices.xml`` and ``99finalDeny.xml``.
The first file contains the default access policy, the latter a single fall through deny rule.
Therefore, you can put your own policies using an additional file in file named 
e.g. *50localRules.xml*.

The policies are reloaded whenever you change (or touch) the configuration file of this PDP, e.g.
like this:

.. code:: console

 $ touch conf/xacml2.conf

