.. table:: 
 :width: 100 
 :widths: 25 20 15 40 
 :class: tight-table

 +----------------------+--------------+----------+--------------------------------------+
 |XACML attribute name  |XACML category|XACML type|Description                           |
 +======================+==============+==========+======================================+
 |\urn:oasis:names:tc:  |Resource      |AnyURI    |WS service name                       |
 |xacml:1.0:resource:   |              |          |                                      |
 |resource\-id          |              |          |                                      |
 +----------------------+--------------+----------+--------------------------------------+
 |\urn:unicore:         |Resource      |String    |Identifier of the WSRF resource       |
 |wsresource            |              |          |instance (if any).                    |
 +----------------------+--------------+----------+--------------------------------------+
 |owner                 |Resource      |X.500 name|The name of the VO resource owner.    |
 +----------------------+--------------+----------+--------------------------------------+
 |voMembership\-VONAME  |Resource      |String    |For each VO the accessed resource is a|
 |                      |              |          |member, there is such attribute with  |
 |                      |              |          |the VONAME set to the VO, and with the|
 |                      |              |          |value specifying allowed access type, |
 |                      |              |          |using the same action categories as   |
 |                      |              |          |are used for the actionType attribute.|
 +----------------------+--------------+----------+--------------------------------------+
 |actionType            |Action        |String    |Action type or category. Currently    |
 |                      |              |          |read for read\-only operation and     |
 |                      |              |          |modify for others.                    |
 +----------------------+--------------+----------+--------------------------------------+
 |\urn:oasis:names:tc:  |Action        |String    |WS operation name.                    |
 |xacml:1.0:action:     |              |          |                                      |
 |action\-id            |              |          |                                      |
 +----------------------+--------------+----------+--------------------------------------+
 |\urn:oasis:names:tc:  |Subject       |X.500 name|User's DN.                            |
 |xacml:1.0:subject:    |              |          |                                      |
 |subject\-id           |              |          |                                      |
 +----------------------+--------------+----------+--------------------------------------+
 |role                  |Subject       |String    |The user's role.                      |
 +----------------------+--------------+----------+--------------------------------------+
 |consignor             |Subject       |X.500 name|Client's (consignor's) DN.            |
 +----------------------+--------------+----------+--------------------------------------+
 |vo                    |Subject       |Strings   |Bag with all VOs the user is member of|
 |                      |              |          |(if any).                             |
 +----------------------+--------------+----------+--------------------------------------+
 |selectedVo            |Subject       |String    |The effective, selected VO (if any).  |
 +----------------------+--------------+----------+--------------------------------------+
