.. table:: 
 :width: 100 
 :widths: 25 15 20 40 
 :class: tight-table

 +-----------------------+--------------+-----------------+--------------------------------------+
 |Property name          |Type          |Default value \/ |Description                           |
 |                       |              |                 |                                      |
 |                       |              |mandatory        |                                      |
 +=======================+==============+=================+======================================+
 |XNJS.staging.curl      |string        |\-               |Location of the curl executable used  |
 |                       |              |                 |                                      |
 |                       |              |                 |for FTP stage\-ins. If null, Java code|
 |                       |              |                 |                                      |
 |                       |              |                 |will be used for FTP.                 |
 +-----------------------+--------------+-----------------+--------------------------------------+
 |XNJS.staging.          |integer \>= 1 |10               |Grace time (in seconds) when waiting  |
 |                       |              |                 |                                      |
 |filesystemGraceTime    |              |                 |for files to appear on shared         |
 |                       |              |                 |                                      |
 |                       |              |                 |filesystems.                          |
 +-----------------------+--------------+-----------------+--------------------------------------+
 |XNJS.staging.gridftp   |string        |globus\-url\-copy|Location of the globus\-url\-copy     |
 |                       |              |                 |                                      |
 |                       |              |                 |executable used for GridFTP staging.  |
 +-----------------------+--------------+-----------------+--------------------------------------+
 |XNJS.staging.          |string        |empty string     |Additional options for globus\-url\-  |
 |                       |              |                 |                                      |
 |gridftpParameters      |              |                 |copy.                                 |
 +-----------------------+--------------+-----------------+--------------------------------------+
 |XNJS.staging.          |[true, false] |false            |Outgoing mail (SMTP): enable SSL      |
 |                       |              |                 |                                      |
 |mailEnableSSL          |              |                 |connection.                           |
 +-----------------------+--------------+-----------------+--------------------------------------+
 |XNJS.staging.mailHost  |string        |localhost        |Outgoing mail host (SMTP) used for    |
 |                       |              |                 |                                      |
 |                       |              |                 |staging\-out via email.               |
 +-----------------------+--------------+-----------------+--------------------------------------+
 |XNJS.staging.          |string        |\-               |Outgoing mail (SMTP) password.        |
 |                       |              |                 |                                      |
 |mailPassword           |              |                 |                                      |
 +-----------------------+--------------+-----------------+--------------------------------------+
 |XNJS.staging.mailPort  |integer number|25               |Outgoing mail (SMTP) port number.     |
 +-----------------------+--------------+-----------------+--------------------------------------+
 |XNJS.staging.          |string        |\-               |Script to be used for sending outgoing|
 |                       |              |                 |                                      |
 |mailSendScript         |              |                 |mail (instead of using SMTP).         |
 +-----------------------+--------------+-----------------+--------------------------------------+
 |XNJS.staging.mailUser  |string        |\-               |Outgoing mail (SMTP) user name.       |
 +-----------------------+--------------+-----------------+--------------------------------------+
 |XNJS.staging.scpWrapper|string        |scp\-wrapper.sh  |Location of the wrapper script used   |
 |                       |              |                 |                                      |
 |                       |              |                 |for scp staging.                      |
 +-----------------------+--------------+-----------------+--------------------------------------+
 |XNJS.staging.threads   |integer \>= 1 |4                |Number of worker threads to use for   |
 |                       |              |                 |                                      |
 |                       |              |                 |data staging.                         |
 +-----------------------+--------------+-----------------+--------------------------------------+
 |XNJS.staging.wget      |string        |\-               |Location of the wget executable used  |
 |                       |              |                 |                                      |
 |                       |              |                 |for HTTP stage\-ins. If null, Java    |
 |                       |              |                 |                                      |
 |                       |              |                 |code will be used for HTTP.           |
 +-----------------------+--------------+-----------------+--------------------------------------+
 |XNJS.staging.          |string        |\-               |Additional options for wget.          |
 |                       |              |                 |                                      |
 |wgetParameters         |              |                 |                                      |
 +-----------------------+--------------+-----------------+--------------------------------------+
