
 .. _java_ciphers: http://docs.oracle.com/javase/8/docs/technotes/guides/security/SunProviders.html#SupportedCipherSuites

.. table:: Jetty settings

   +------------------------+-------------+---------------+-------------------------------------+
   | Property name          | Type        | Default value | Description                         |
   |                        |             |               |                                     |
   |                        |             | \/ mandatory  |                                     |
   +========================+=============+===============+=====================================+
   | gateway.httpServer.    | string      | \*            | CORS: comma separated list of       |
   |                        |             |               |                                     |
   | CORS_allowedHeaders    |             |               | allowed HTTP headers (default: any) |
   +------------------------+-------------+---------------+-------------------------------------+
   | gateway.httpServer.    | string      | GET,PUT,POST, | CORS: comma separated list of       |
   |                        |             |               |                                     |
   | CORS_allowedMethods    |             | DELETE,HEAD   | allowed HTTP verbs.                 |
   +------------------------+-------------+---------------+-------------------------------------+
   | gateway.httpServer.    | string      | \*            | CORS: allowed script origins.       |
   |                        |             |               |                                     |
   | CORS_allowedOrigins    |             |               |                                     |
   +------------------------+-------------+---------------+-------------------------------------+
   | gateway.httpServer.    | [true,      | false         | CORS: whether preflight OPTION      |
   |                        |             |               |                                     |
   | CORS_chainPreflight    | false]      |               | requests are chained (passed on) to |
   |                        |             |               |                                     |
   |                        |             |               | the resource or handled via the     |
   |                        |             |               |                                     |
   |                        |             |               | CORS filter.                        |
   +------------------------+-------------+---------------+-------------------------------------+
   | gateway.httpServer.    | string      | Location,     | CORS: comma separated list of HTTP  |
   |                        |             |               |                                     |
   | CORS_exposedHeaders    |             | Content-Type  | headers that are allowed to be      |
   |                        |             |               |                                     |
   |                        |             |               | exposed to the client.              |
   +------------------------+-------------+---------------+-------------------------------------+
   | gateway.httpServer.    | string      | empty string  | Space separated list of SSL cipher  |
   |                        |             |               |                                     |
   | disabledCipherSuites   |             |               | suites to be disabled. Names of the |
   |                        |             |               |                                     |
   |                        |             |               | ciphers must adhere to the standard |
   |                        |             |               |                                     |
   |                        |             |               | Java cipher names, available here:  |
   |                        |             |               |                                     |
   |                        |             |               | java_ciphers_                       |
   +------------------------+-------------+---------------+-------------------------------------+
   | gateway.httpServer.    | [true,      | false         | Control whether Cross-Origin        |
   |                        |             |               |                                     |
   | enableCORS             | false]      |               | Resource Sharing is enabled. Enable |
   |                        |             |               |                                     |
   |                        |             |               | to allow e.g. accesing REST         |
   |                        |             |               |                                     |
   |                        |             |               | services from client-side           |
   |                        |             |               |                                     |
   |                        |             |               | JavaScript.                         |
   +------------------------+-------------+---------------+-------------------------------------+
   | gateway.httpServer.    | [true,      | false         | Control whether HTTP strict         |
   |                        |             |               |                                     |
   | enableHsts             | false]      |               | transport security is enabled. It   |
   |                        |             |               |                                     |
   |                        |             |               | is a good and strongly suggested    |
   |                        |             |               |                                     |
   |                        |             |               | security mechanism for all          |
   |                        |             |               |                                     |
   |                        |             |               | production sites. At the same time  |
   |                        |             |               |                                     |
   |                        |             |               | it can not be used with self-signed |
   |                        |             |               |                                     |
   |                        |             |               | or not issued by a generally        |
   |                        |             |               |                                     |
   |                        |             |               | trusted CA server certificates, as  |
   |                        |             |               |                                     |
   |                        |             |               | with HSTS a user can’t opt in to    |
   |                        |             |               |                                     |
   |                        |             |               | enter such site.                    |
   +------------------------+-------------+---------------+-------------------------------------+
   | gateway.httpServer.    | [true,      | false         | Use insecure, but fast pseudo       |
   |                        |             |               |                                     |
   | fastRandom             | false]      |               | random generator to generate        |
   |                        |             |               |                                     |
   |                        |             |               | session ids  instead of secure      |
   |                        |             |               |                                     |
   |                        |             |               | generator for SSL sockets.          |
   +------------------------+-------------+---------------+-------------------------------------+
   | gateway.httpServer.    | [true,      | false         | Controls whether to enable          |
   |                        |             |               |                                     |
   | gzip.enable            | false]      |               | compression of HTTP responses.      |
   +------------------------+-------------+---------------+-------------------------------------+
   | gateway.httpServer.    | integer     | 100000        | Specifies the minimal size of       |
   |                        |             |               |                                     |
   | gzip.minGzipSize       | number      |               | message that should be compressed.  |
   +------------------------+-------------+---------------+-------------------------------------+
   | gateway.httpServer.    | integer     | 200           | deprecated                          |
   |                        |             |               |                                     |
   | highLoadConnections    | number      |               |                                     |
   +------------------------+-------------+---------------+-------------------------------------+
   | gateway.httpServer.    | integer     | 100           | deprecated                          |
   |                        |             |               |                                     |
   | lowResourceMaxIdleTime | \>= 1       |               |                                     |
   +------------------------+-------------+---------------+-------------------------------------+
   | gateway.httpServer.    | integer     | 0             | Maximum number of incoming          |
   |                        |             |               |                                     |
   | maxConnections         | \>= 0       |               | connections to this server. If set  |
   |                        |             |               |                                     |
   |                        |             |               | to a value larger than 0, incoming  |
   |                        |             |               |                                     |
   |                        |             |               | connections will be limited to that |
   |                        |             |               |                                     |
   |                        |             |               | number. Default is 0 = unlimited.   |
   +------------------------+-------------+---------------+-------------------------------------+
   | gateway.httpServer.    | integer     | 200000        | Time (in ms.) before an idle        |
   |                        |             |               |                                     |
   | maxIdleTime            | \>= 1       |               | connection will time out. It should |
   |                        |             |               |                                     |
   |                        |             |               | be large enough not to expire       |
   |                        |             |               |                                     |
   |                        |             |               | connections with slow clients,      |
   |                        |             |               |                                     |
   |                        |             |               | values below 30s are getting quite  |
   |                        |             |               |                                     |
   |                        |             |               | risky.                              |
   +------------------------+-------------+---------------+-------------------------------------+
   | gateway.httpServer.    | integer     | 255           | Maximum number of threads to have   |
   |                        |             |               |                                     |
   | maxThreads             | number      |               | in the thread pool for processing   |
   |                        |             |               |                                     |
   |                        |             |               | HTTP connections. Note that this    |
   |                        |             |               |                                     |
   |                        |             |               | number will be increased with few   |
   |                        |             |               |                                     |
   |                        |             |               | additional threads to handle        |
   |                        |             |               |                                     |
   |                        |             |               | connectors.                         |
   +------------------------+-------------+---------------+-------------------------------------+
   | gateway.httpServer.    | integer     | 1             | Minimum number of threads to have   |
   |                        |             |               |                                     |
   | minThreads             | \>= 1       |               | in the thread pool for processing   |
   |                        |             |               |                                     |
   |                        |             |               | HTTP connections. Note that this    |
   |                        |             |               |                                     |
   |                        |             |               | number will be increased with few   |
   |                        |             |               |                                     |
   |                        |             |               | additional threads to handle        |
   |                        |             |               |                                     |
   |                        |             |               | connectors.                         |
   +------------------------+-------------+---------------+-------------------------------------+
   | gateway.httpServer.    | [true,      | true          | Controls whether the SSL socket     |
   |                        |             |               |                                     |
   | requireClientAuthn     | false]      |               | requires client-side authentication.|
   +------------------------+-------------+---------------+-------------------------------------+
   | gateway.httpServer.    | [true,      | true          | DEPRECATED, no effect               |
   |                        |             |               |                                     |
   | useNIO                 | false]      |               |                                     |
   +------------------------+-------------+---------------+-------------------------------------+
   | gateway.httpServer.    | [true,      | true          | Controls whether the SSL socket     |
   |                        |             |               |                                     |
   | wantClientAuthn        | false]      |               | accepts (but does not require)      |
   |                        |             |               |                                     |
   |                        |             |               | client-side authentication.         |
   +------------------------+-------------+---------------+-------------------------------------+
   | gateway.httpServer.    | string      | http:\/\/     | URI origin that is allowed to embed |
   |                        |             |               |                                     |
   | xFrameAllowed          |             | localhost     | web interface inside a (i)frame.    |
   |                        |             |               |                                     |
   |                        |             |               | Meaningful only if the              |
   |                        |             |               |                                     |
   |                        |             |               | xFrameOptions is set to allowFrom.  |
   |                        |             |               |                                     |
   |                        |             |               | The value should be in the form:    |
   |                        |             |               |                                     |
   |                        |             |               | http[s]:\/\/host[:port]             |
   +------------------------+-------------+---------------+-------------------------------------+
   | gateway.httpServer.    | [deny,      | deny          | Defines whether a clickjacking      |
   |                        |             |               |                                     |
   | xFrameOptions          | sameOrigin, |               | prevention should be turned on, by  |
   |                        |             |               |                                     |
   |                        | allowFrom,  |               | insertionof the X-Frame-Options     |
   |                        |             |               |                                     |
   |                        | allow]      |               | HTTP header. The allow value        |
   |                        |             |               |                                     |
   |                        |             |               | disables the feature. See the RFC   |
   |                        |             |               |                                     |
   |                        |             |               | 7034 for details. Note that for the |
   |                        |             |               |                                     |
   |                        |             |               | allowFrom you should define also    |
   |                        |             |               |                                     |
   |                        |             |               | the xFrameAllowed option and it is  |
   |                        |             |               |                                     |
   |                        |             |               | not fully supported by all the      |
   |                        |             |               |                                     |
   |                        |             |               | browsers.                           |
   +------------------------+-------------+---------------+-------------------------------------+
 
 
