.. table:: 
 :width: 100 
 :widths: 30 20 50 
 :class: tight-table

 +------------------------------------+-----------------+------------------------------------------------+
 |Tag                                 |Type             |Description                                     |
 +====================================+=================+================================================+
 |ApplicationName                     |String           |Application name                                |
 +------------------------------------+-----------------+------------------------------------------------+
 |ApplicationVersion                  |String           |Application version                             |
 +------------------------------------+-----------------+------------------------------------------------+
 |Executable                          |String           |Command line                                    |
 +------------------------------------+-----------------+------------------------------------------------+
 |Arguments                           |List of strings  |Command line arguments                          |
 +------------------------------------+-----------------+------------------------------------------------+
 |Environment                         |Map of strings   |Environment values                              |
 +------------------------------------+-----------------+------------------------------------------------+
 |Parameters                          |Map              |Application parameters                          |
 +------------------------------------+-----------------+------------------------------------------------+
 |Stdout                              |String           |Filename for the standard output (default:      |
 |                                    |                 |"stdout")                                       |
 +------------------------------------+-----------------+------------------------------------------------+
 |Stderr                              |String           |Filename for the standard error (default:       |
 |                                    |                 |"stderr")                                       |
 +------------------------------------+-----------------+------------------------------------------------+
 |Stdin                               |String           |Filename for the standard input (optional)      |
 +------------------------------------+-----------------+------------------------------------------------+
 |IgnoreNonZeroExitCode               |"true" \/ "false"|Don't fail the job if app exits with non\-zero  |
 |                                    |                 |exit code (default: false)                      |
 +------------------------------------+-----------------+------------------------------------------------+
 |User precommand                     |String           |Pre\-processing                                 |
 +------------------------------------+-----------------+------------------------------------------------+
 |RunUserPrecommandOnLoginNode        |"true"\/"false"  |Pre\-processing is done on login node (default: |
 |                                    |                 |true)                                           |
 +------------------------------------+-----------------+------------------------------------------------+
 |UserPrecommandIgnoreNonZeroExitCode |"true"\/"false"  |Don't fail job if pre\-command fails (default:  |
 |                                    |                 |false)                                          |
 +------------------------------------+-----------------+------------------------------------------------+
 |User postcommand                    |String           |Post\-processing                                |
 +------------------------------------+-----------------+------------------------------------------------+
 |RunUserPostcommandOnLoginNode       |"true" \/ "false"|Post\-processing is done on login node (default:|
 |                                    |                 |true)                                           |
 +------------------------------------+-----------------+------------------------------------------------+
 |UserPostcommandIgnoreNonZeroExitCode|"true"\/"false"  |Don't fail job if post\-command fails (default: |
 |                                    |                 |false)                                          |
 +------------------------------------+-----------------+------------------------------------------------+
 |Resources                           |Map              |The job's resource requests                     |
 +------------------------------------+-----------------+------------------------------------------------+
 |Project                             |String           |Accounting project                              |
 +------------------------------------+-----------------+------------------------------------------------+
 |Imports                             |List of imports  |Stage\-in \/ data import                        |
 +------------------------------------+-----------------+------------------------------------------------+
 |Exports                             |List of exports  |Stage\-out \/ data export                       |
 +------------------------------------+-----------------+------------------------------------------------+
 |haveClientStageIn                   |"true" \/ "false"|Tell the server that the client does \/ does not|
 |                                    |                 |want to send any additional files               |
 +------------------------------------+-----------------+------------------------------------------------+
 |Job type                            |'batch',         |Whether to run the job via the batch system     |
 |                                    |'on_login_node', |('batch', default) or on a login node           |
 |                                    |'raw',           |('on_login_node'), or as a batch job with       |
 |                                    |'allocate'       |user\-specified file containing the batch       |
 |                                    |                 |batch system directives ('raw'), or to only     |
 |                                    |                 |'allocate' resoures but not start anything      |
 +------------------------------------+-----------------+------------------------------------------------+
 |Login node                          |String           |For 'on_login_node' jobs, select a login node   |
 |                                    |                 |by name, as configured server side. Wildcards   |
 |                                    |                 |'\*' and '?' can be used)                       |
 +------------------------------------+-----------------+------------------------------------------------+
 |BSS file                            |String           |For 'raw' jobs, specify the relative or absolute|
 |                                    |                 |file name of a file containing batch system     |
 |                                    |                 |directives. UNICORE will append the user        |
 |                                    |                 |executable.                                     |
 +------------------------------------+-----------------+------------------------------------------------+
 |Tags                                |List of strings  |Job tags                                        |
 +------------------------------------+-----------------+------------------------------------------------+
 |Notification                        |String           |URL to send job status change notifications to  |
 |                                    |                 |(via HTTP POST)                                 |
 +------------------------------------+-----------------+------------------------------------------------+
 |User email                          |String           |User email to send notifications to (if the     |
 |                                    |                 |batch system supports it)                       |
 +------------------------------------+-----------------+------------------------------------------------+
 |Name                                |String           |Job name                                        |
 +------------------------------------+-----------------+------------------------------------------------+
